### ISSUE TITLE
can't join to admin panel

### ISSUE THREAD

**Issue by Petr2016** [hoelsner/product-database#1]
Hi team,

I meet with issue that I can't login into admin panel. Combination admin\admin is not accept. I tryied different methods and tricks, but still didn't have access. Could you please help with this issue?

**Comment by hoelsner** [comment]
Hi Petr, 

I need to change the default user in the latest version because of the optional LDAP integration. Please try the new username **pdb_admin** and the password **pdb_admin**.

Kind regards, Henry

**Comment by Petr2016** [comment]
Hi Henry!

Thank you for fast reply! It's work! Thank you a lot!

Best regards, Petr
