### ISSUE TITLE
Not an issue, but question about EoX sync process

### ISSUE THREAD

**Issue by andrepferreira** [hoelsner/product-database#22]
Hi there

I don't think I understand the EoX sync process correctly, but should I be able to automatically update the EoX local data every week with this feature? I have a fairly static list of products loaded in a list that I want to monitor for items that go EoX. For this, the EoX data needs to be refreshed regularly. Can the sync function do this? 

Thanks

**Comment by hoelsner** [comment]
Hi, 
if you enable the automatic synchronisation at "Admin" > "Settings", the EoX data are updated every week. You can add the Products to the database that you like to monitor and if these are valid Cisco SKUs, the EoX state regularly updated. 
Kind regards,
Henry
