### ISSUE TITLE
Search with special symbols

### ISSUE THREAD

**Issue by Petr2016** [hoelsner/product-database#3]
Hello Henry,

I'm found out one interesting issue: when I try to search by product ID Cisco LineCard: 7600-ES+4TG3CXL it is didn't iclude in search results but exist in local product database. If I spell only 7600-ES+ without any additional symbols I could find this linecard in search results. Any symbols after "+" is ignored. Simillar situation I found with Linecard 76-ES+.

Thank you.

WBR
Petr

**Comment by Petr2016** [comment]
As I find clue it is combination in Product ID 2 symbols "-" and "+"
If I try to find information about WS-C2960+48PST-L - I got same results. Nothing founded.

WBR
Petr

**Comment by hoelsner** [comment]
Hi Petr, 

the reason for this behavior is that the search functions always check if the value is a valid regular expression. If so, the database search is performed using regex, if not a simple like search is performed. The special symbols are therefore interpreted as part of the regular expression. The `+` in this case is interpreted as one or more of the previous characters during the search. 

If you escape the special symbols (adding backslashes before the symbols), it should work, e.g. with `7600\-ES\+4TG3CXL`

I'm not sure if this implementation is useful in the long run. Maybe I should add an user profile option to choose between the like and the regular expression search. What's your opinion on this?

Kind regards, 
Henry

**Comment by Petr2016** [comment]
Hi Henry,

I'm not sure that I clear understand your idea about implement choose between simple search and regular expression search. I suggest the root of my poor experience in english. But, I would like to share with you my experience - I show your productDB to my friends (colleagues) - they always copy-paste partnumber of device from specification\documentation\etc to search string. No one think about regular expression. If you think about long terms you could add into Profile Settings checkbox which enable search by regular expression, but by default it is preffered simple like search.
P.S. I'm check search with backslashes - all work properly ) You're right.
P.P.S. I'm totally newbie in Django&Python and for me it is very hard to understand ho to do some changes. Could you please give me first clue in which direction I need to go to a little bit start understand what happines on the Backend ProductDB with Cisco API. First of all my little target try to add to database schema "EOXMigrationDetails" and display it in some colums in search results. As you recommended it to Vladimir some times ago. 

WBR
Petr

**Comment by hoelsner** [comment]
Hi Petr, 

okay, I'll add user profile settings with an option to change the default search operation (like or regular expression) in the next release. 

The entire import form the EoX API is implemented in the `update_local_db_based_on_record()` function in the [app.ciscoeox.api_crawler](https://github.com/hoelsner/product-database/blob/master/app/ciscoeox/api_crawler.py) module. I plan to add the migration data in the next version, just to make sure that we don't do the work twice. 

Kind regards, 
Henry

**Comment by Petr2016** [comment]
Hi Henry,

Yeah I read abot your roadmap into your blog. I wanna do this job just for educational purpose. Thank you for reply and getting clue. 
I done great job!
P.S. I'm not sure this is right way, but if I will have some ideas or suggestions for improvement could I post it here as Issue? Or use your blog?

**Comment by hoelsner** [comment]
Hi Petr, 

if you have any issue, idea or suggestion for improvement, please post an issue here on GitHub. Thank you. 

Regards, Henry
