### ISSUE TITLE
vagrant not able to provision

### ISSUE THREAD

**Issue by edurguti** [hoelsner/product-database#4]
Hi
Im getting the following error when using vagrant, im on masOS.

Im getting the following when using vagrant.

==> productdb: Reading state information...
==> productdb: python is already the newest version (2.7.11-1).
==> productdb: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> productdb: Running provisioner: ansible...
productdb: Running ansible-playbook...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your host system.

If you haven't installed Ansible yet, please install Ansible
on your host system. Vagrant can't do this for you in a safe and
automated way.
Please check https://docs.ansible.com for more information.

**Comment by hoelsner** [comment]
Hi edurguti, 

I think you don't have Ansible installed on you Mac. Vagrant needs it to start the provisioning process. Can you please check your ansible version with the `ansible --version` terminal command.

Greetings, 
Henry

**Comment by edurguti** [comment]
Hi, Yeah I didn't have ansible on my mac, however I figured how to run the playbook locally on the vagrant guest.
Thanks for your prompt reply.

**Comment by hoelsner** [comment]
Hi, okay. I will close this case.
