### ISSUE TITLE
Cisco API issue

### ISSUE THREAD

**Issue by edurguti** [hoelsner/product-database#5]
Hi, I have successfully registered with EOX API but when I add the credentials it is failing:

"Cannot contact the Cisco EoX API. Please contact your Administrator"
are there any logs I can actually see what the error is?

**Comment by hoelsner** [comment]
Hi edurguti, 

yes, there are logs stored at `/var/www/productdb/logs`. Please take a look at the `celery_worker.log` file. This file contains the python traceback that shows the reason, why the synchronisation failed. 

Greetings, Henry

**Comment by edurguti** [comment]
interestingly enough it just worked with EoX API v5. thank you
