### ISSUE TITLE
OS version to run your app

### ISSUE THREAD

**Issue by sebd44** [hoelsner/product-database#8]
Hi Hoelsner, i hope you are doing well
well i have a question i read the dockerfile and it says ubuntu, only in ubuntu machine i can run you are app? and thinks is a wonderful app.

because in the setup & installation

docker build -f deploy/docker/Dockerfile-basebox -t productdb/basebox:latest .

i run this command but shows me a lstat error
and in the deploy/docker folder i have this files::

uild_deps  django  Dockerfile-build_deps  Dockerfile-django  Dockerfile-nginx  Dockerfile-postgres  nginx  postgres

can you help me please, best regards

**Comment by hoelsner** [comment]
Hi @sebd44, 

you can run the webservice on any OS that is able to run Docker (visit the [Supported Platforms - Docker Documentation](https://docs.docker.com/install/#supported-platforms) for details). The ubuntu statement in the Dockerfile is just the base image for the containers that are build.

I removed the basebox a while ago. Please use the release tag [v0.9](https://github.com/hoelsner/product-database/releases/tag/v0.9) that was created just now.

To build and run the application on a Docker host, just execute the following commands on the server:

```bash
cp env.prod_template env.myinstance
# it is recommended to change the default values within the env.myinstance (plschgme values)
export COMPOSE_PROJECT_NAME=productdb
export INSTANCE_CONFIG=myinstance
docker-compose up -d
```

The app is reachable after the `build_deps` container exited.

Best regards, Henry

**Comment by sebd44** [comment]
Hi Hoelsner, thanks a lot for those commands and guide, because the docker-compose started, but i think i'm missing one env $PATH, everything went well, but after reaching this point the build of the images stopped asking for this: "executable file not found in $PATH""

productdb_database is up-to-date
Starting productdb_build_deps ... 
Starting productdb_build_deps ... done
Starting productdb_beat       ... 
Starting productdb_camera     ... 
Starting productdb_web_1      ... error

ERROR: for productdb_web_1  Cannot start service web: oci runtime error: container_linux.go:247: starting container process caused "exec: \"start_gunicorn\": executStarting productdb_camera     ... error


Starting productdb_beat       ... error
": executable file not found in $PATH"


ERROR: for productdb_beat  Cannot start service beat: oci runtime error: container_linux.go:247: starting container process caused "exec: \"start_celery_beat\": executable file not found in $PATH"


ERROR: for beat  Cannot start service beat: oci runtime error: container_linux.go:247: starting container process caused "exec: \"start_celery_beat\": executable file not found in $PATH"


ERROR: for web  Cannot start service web: oci runtime error: container_linux.go:247: starting container process caused "exec: \"start_gunicorn\": executable file not found in $PATH"


ERROR: for camera  Cannot start service camera: oci runtime error: container_linux.go:247: starting container process caused "exec: \"start_celery_camera\": executable file not found in $PATH"

ERROR: Encountered errors while bringing up the project.

**Comment by hoelsner** [comment]
Hi @sebd44,

after you pull the code from github, you need to rebuild the docker containers using the following command:

```
docker-compose build
```

Then you can use the `docker-compose up -d` command and it should work.

Best regards,
Henry
